name: qmanagement
description: A new Flutter application.

publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  fluttertoast: ^4.0.0
  shared_preferences: ^0.5.3
  http: any
  connectivity: ^0.4.0+16
  provider: ^3.1.0
  package_info: ^0.4.0+16
  date_format: 1.0.8
  image_picker: ^0.5.3+1
  url_launcher : ^5.4.10
  store_redirect: ^1.0.2
  flutter_datetime_picker: ^1.3.8

#  Search SCANNER_LIBRARY_CHECK in project
  # for Android
 # flutter_barcode_scanner: ^1.0.1
  # for iOS
 # flutter_barcode_scanner: ^0.0.9

  qrscan: ^0.2.19
  firebase_messaging: ^5.1.2
  flutter_local_notifications:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/font/CustomIcons.ttf

  assets:
      - lang/en.json
      - lang/hi.json
      - assets/images/img_splash.png
      - assets/images/img_logo.png
      - assets/images/ic_logo_sign.png
      - assets/images/bg_top_login.png
      - assets/images/bg_top_home.png
      - assets/images/img_logo_login.png
      - assets/images/img_pass.png
      - assets/images/ic_cam.png